spring:
  application:
    name: teacher-server
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:9411
  datasource:
    url: jdbc:mysql://111.230.199.112:3306/cloudtest?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false
    username: test123
    password: Test#@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka/
